//#line 2 "/opt/ros/jade/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the ahl_robot_samples package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __ahl_robot_samples__REDARMPARAMCONFIG_H__
#define __ahl_robot_samples__REDARMPARAMCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace ahl_robot_samples
{
  class RedArmParamConfigStatics;
  
  class RedArmParamConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(RedArmParamConfig &config, const RedArmParamConfig &max, const RedArmParamConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const RedArmParamConfig &config1, const RedArmParamConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, RedArmParamConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const RedArmParamConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, RedArmParamConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const RedArmParamConfig &config) const = 0;
      virtual void getValue(const RedArmParamConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T RedArmParamConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (RedArmParamConfig::* field);

      virtual void clamp(RedArmParamConfig &config, const RedArmParamConfig &max, const RedArmParamConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const RedArmParamConfig &config1, const RedArmParamConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, RedArmParamConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const RedArmParamConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, RedArmParamConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const RedArmParamConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const RedArmParamConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, RedArmParamConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, RedArmParamConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<RedArmParamConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(RedArmParamConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class RED_ARM_PARAM
{
  public:
    RED_ARM_PARAM()
    {
      state = true;
      name = "red_arm_param";
    }

    void setParams(RedArmParamConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("show_target"==(*_i)->name){show_target = boost::any_cast<bool>(val);}
        if("sin_x"==(*_i)->name){sin_x = boost::any_cast<bool>(val);}
        if("sin_y"==(*_i)->name){sin_y = boost::any_cast<bool>(val);}
        if("sin_z"==(*_i)->name){sin_z = boost::any_cast<bool>(val);}
        if("x_arm"==(*_i)->name){x_arm = boost::any_cast<double>(val);}
        if("y_arm"==(*_i)->name){y_arm = boost::any_cast<double>(val);}
        if("z_arm"==(*_i)->name){z_arm = boost::any_cast<double>(val);}
        if("roll_arm"==(*_i)->name){roll_arm = boost::any_cast<double>(val);}
        if("pitch_arm"==(*_i)->name){pitch_arm = boost::any_cast<double>(val);}
        if("yaw_arm"==(*_i)->name){yaw_arm = boost::any_cast<double>(val);}
        if("q1"==(*_i)->name){q1 = boost::any_cast<double>(val);}
        if("q2"==(*_i)->name){q2 = boost::any_cast<double>(val);}
        if("q3"==(*_i)->name){q3 = boost::any_cast<double>(val);}
        if("q4"==(*_i)->name){q4 = boost::any_cast<double>(val);}
        if("q5"==(*_i)->name){q5 = boost::any_cast<double>(val);}
        if("q6"==(*_i)->name){q6 = boost::any_cast<double>(val);}
        if("q7"==(*_i)->name){q7 = boost::any_cast<double>(val);}
      }
    }

    bool show_target;
bool sin_x;
bool sin_y;
bool sin_z;
double x_arm;
double y_arm;
double z_arm;
double roll_arm;
double pitch_arm;
double yaw_arm;
double q1;
double q2;
double q3;
double q4;
double q5;
double q6;
double q7;

    bool state;
    std::string name;

    
}red_arm_param;

}groups;



//#line 10 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      bool show_target;
//#line 11 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      bool sin_x;
//#line 12 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      bool sin_y;
//#line 13 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      bool sin_z;
//#line 15 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      double x_arm;
//#line 16 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      double y_arm;
//#line 17 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      double z_arm;
//#line 19 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      double roll_arm;
//#line 20 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      double pitch_arm;
//#line 21 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      double yaw_arm;
//#line 23 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      double q1;
//#line 24 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      double q2;
//#line 25 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      double q3;
//#line 26 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      double q4;
//#line 27 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      double q5;
//#line 28 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      double q6;
//#line 29 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      double q7;
//#line 218 "/opt/ros/jade/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("RedArmParamConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const RedArmParamConfig &__max__ = __getMax__();
      const RedArmParamConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const RedArmParamConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const RedArmParamConfig &__getDefault__();
    static const RedArmParamConfig &__getMax__();
    static const RedArmParamConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const RedArmParamConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void RedArmParamConfig::ParamDescription<std::string>::clamp(RedArmParamConfig &config, const RedArmParamConfig &max, const RedArmParamConfig &min) const
  {
    return;
  }

  class RedArmParamConfigStatics
  {
    friend class RedArmParamConfig;
    
    RedArmParamConfigStatics()
    {
RedArmParamConfig::GroupDescription<RedArmParamConfig::DEFAULT, RedArmParamConfig> Default("Default", "", 0, 0, true, &RedArmParamConfig::groups);
RedArmParamConfig::GroupDescription<RedArmParamConfig::DEFAULT::RED_ARM_PARAM, RedArmParamConfig::DEFAULT> red_arm_param("red_arm_param", "", 0, 1, true, &RedArmParamConfig::DEFAULT::red_arm_param);
//#line 10 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __min__.show_target = 0;
//#line 10 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __max__.show_target = 1;
//#line 10 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __default__.show_target = 1;
//#line 10 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      red_arm_param.abstract_parameters.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<bool>("show_target", "bool", 0, "Show reference position", "", &RedArmParamConfig::show_target)));
//#line 10 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __param_descriptions__.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<bool>("show_target", "bool", 0, "Show reference position", "", &RedArmParamConfig::show_target)));
//#line 11 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __min__.sin_x = 0;
//#line 11 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __max__.sin_x = 1;
//#line 11 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __default__.sin_x = 0;
//#line 11 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      red_arm_param.abstract_parameters.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<bool>("sin_x", "bool", 0, "desired x sin wave", "", &RedArmParamConfig::sin_x)));
//#line 11 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __param_descriptions__.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<bool>("sin_x", "bool", 0, "desired x sin wave", "", &RedArmParamConfig::sin_x)));
//#line 12 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __min__.sin_y = 0;
//#line 12 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __max__.sin_y = 1;
//#line 12 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __default__.sin_y = 0;
//#line 12 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      red_arm_param.abstract_parameters.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<bool>("sin_y", "bool", 0, "desired y sin wave", "", &RedArmParamConfig::sin_y)));
//#line 12 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __param_descriptions__.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<bool>("sin_y", "bool", 0, "desired y sin wave", "", &RedArmParamConfig::sin_y)));
//#line 13 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __min__.sin_z = 0;
//#line 13 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __max__.sin_z = 1;
//#line 13 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __default__.sin_z = 0;
//#line 13 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      red_arm_param.abstract_parameters.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<bool>("sin_z", "bool", 0, "desired z sin wave", "", &RedArmParamConfig::sin_z)));
//#line 13 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __param_descriptions__.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<bool>("sin_z", "bool", 0, "desired z sin wave", "", &RedArmParamConfig::sin_z)));
//#line 15 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __min__.x_arm = -3.0;
//#line 15 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __max__.x_arm = 3.0;
//#line 15 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __default__.x_arm = 0.42;
//#line 15 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      red_arm_param.abstract_parameters.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("x_arm", "double", 0, "desired x for gripper", "", &RedArmParamConfig::x_arm)));
//#line 15 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __param_descriptions__.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("x_arm", "double", 0, "desired x for gripper", "", &RedArmParamConfig::x_arm)));
//#line 16 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __min__.y_arm = -3.0;
//#line 16 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __max__.y_arm = 3.0;
//#line 16 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __default__.y_arm = 0.24;
//#line 16 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      red_arm_param.abstract_parameters.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("y_arm", "double", 0, "desired y for gripper", "", &RedArmParamConfig::y_arm)));
//#line 16 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __param_descriptions__.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("y_arm", "double", 0, "desired y for gripper", "", &RedArmParamConfig::y_arm)));
//#line 17 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __min__.z_arm = 0.0;
//#line 17 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __max__.z_arm = 1.0;
//#line 17 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __default__.z_arm = 0.36;
//#line 17 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      red_arm_param.abstract_parameters.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("z_arm", "double", 0, "desired z for gripper", "", &RedArmParamConfig::z_arm)));
//#line 17 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __param_descriptions__.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("z_arm", "double", 0, "desired z for gripper", "", &RedArmParamConfig::z_arm)));
//#line 19 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __min__.roll_arm = -3.14;
//#line 19 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __max__.roll_arm = 3.14;
//#line 19 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __default__.roll_arm = 0.0;
//#line 19 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      red_arm_param.abstract_parameters.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("roll_arm", "double", 0, "desired roll  for gripper", "", &RedArmParamConfig::roll_arm)));
//#line 19 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __param_descriptions__.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("roll_arm", "double", 0, "desired roll  for gripper", "", &RedArmParamConfig::roll_arm)));
//#line 20 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __min__.pitch_arm = -3.14;
//#line 20 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __max__.pitch_arm = 3.14;
//#line 20 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __default__.pitch_arm = 3.14;
//#line 20 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      red_arm_param.abstract_parameters.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("pitch_arm", "double", 0, "desired pitch for gripper", "", &RedArmParamConfig::pitch_arm)));
//#line 20 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __param_descriptions__.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("pitch_arm", "double", 0, "desired pitch for gripper", "", &RedArmParamConfig::pitch_arm)));
//#line 21 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __min__.yaw_arm = -3.14;
//#line 21 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __max__.yaw_arm = 3.14;
//#line 21 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __default__.yaw_arm = 0.0;
//#line 21 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      red_arm_param.abstract_parameters.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("yaw_arm", "double", 0, "desired yaw   for gripper", "", &RedArmParamConfig::yaw_arm)));
//#line 21 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __param_descriptions__.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("yaw_arm", "double", 0, "desired yaw   for gripper", "", &RedArmParamConfig::yaw_arm)));
//#line 23 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __min__.q1 = -3.14;
//#line 23 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __max__.q1 = 3.14;
//#line 23 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __default__.q1 = 0.0;
//#line 23 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      red_arm_param.abstract_parameters.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("q1", "double", 0, "angle of arm joint1", "", &RedArmParamConfig::q1)));
//#line 23 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __param_descriptions__.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("q1", "double", 0, "angle of arm joint1", "", &RedArmParamConfig::q1)));
//#line 24 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __min__.q2 = -3.14;
//#line 24 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __max__.q2 = 3.14;
//#line 24 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __default__.q2 = 0.5;
//#line 24 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      red_arm_param.abstract_parameters.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("q2", "double", 0, "angle of arm joint2", "", &RedArmParamConfig::q2)));
//#line 24 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __param_descriptions__.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("q2", "double", 0, "angle of arm joint2", "", &RedArmParamConfig::q2)));
//#line 25 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __min__.q3 = -3.14;
//#line 25 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __max__.q3 = 3.14;
//#line 25 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __default__.q3 = 0.0;
//#line 25 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      red_arm_param.abstract_parameters.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("q3", "double", 0, "angle of arm joint3", "", &RedArmParamConfig::q3)));
//#line 25 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __param_descriptions__.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("q3", "double", 0, "angle of arm joint3", "", &RedArmParamConfig::q3)));
//#line 26 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __min__.q4 = -3.14;
//#line 26 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __max__.q4 = 3.14;
//#line 26 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __default__.q4 = -0.5;
//#line 26 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      red_arm_param.abstract_parameters.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("q4", "double", 0, "angle of arm joint4", "", &RedArmParamConfig::q4)));
//#line 26 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __param_descriptions__.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("q4", "double", 0, "angle of arm joint4", "", &RedArmParamConfig::q4)));
//#line 27 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __min__.q5 = -3.14;
//#line 27 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __max__.q5 = 3.14;
//#line 27 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __default__.q5 = 0.0;
//#line 27 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      red_arm_param.abstract_parameters.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("q5", "double", 0, "angle of arm joint5", "", &RedArmParamConfig::q5)));
//#line 27 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __param_descriptions__.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("q5", "double", 0, "angle of arm joint5", "", &RedArmParamConfig::q5)));
//#line 28 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __min__.q6 = -3.14;
//#line 28 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __max__.q6 = 3.14;
//#line 28 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __default__.q6 = 0.5;
//#line 28 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      red_arm_param.abstract_parameters.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("q6", "double", 0, "angle of arm joint5", "", &RedArmParamConfig::q6)));
//#line 28 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __param_descriptions__.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("q6", "double", 0, "angle of arm joint5", "", &RedArmParamConfig::q6)));
//#line 29 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __min__.q7 = -3.14;
//#line 29 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __max__.q7 = 3.14;
//#line 29 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __default__.q7 = 0.0;
//#line 29 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      red_arm_param.abstract_parameters.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("q7", "double", 0, "angle of arm joint5", "", &RedArmParamConfig::q7)));
//#line 29 "/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/ahl_wbc/samples/ahl_robot_samples/cfg/RedArmParam.cfg"
      __param_descriptions__.push_back(RedArmParamConfig::AbstractParamDescriptionConstPtr(new RedArmParamConfig::ParamDescription<double>("q7", "double", 0, "angle of arm joint5", "", &RedArmParamConfig::q7)));
//#line 109 "/opt/ros/jade/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      red_arm_param.convertParams();
//#line 109 "/opt/ros/jade/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(RedArmParamConfig::AbstractGroupDescriptionConstPtr(new RedArmParamConfig::GroupDescription<RedArmParamConfig::DEFAULT::RED_ARM_PARAM, RedArmParamConfig::DEFAULT>(red_arm_param)));
//#line 109 "/opt/ros/jade/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(RedArmParamConfig::AbstractGroupDescriptionConstPtr(new RedArmParamConfig::GroupDescription<RedArmParamConfig::DEFAULT::RED_ARM_PARAM, RedArmParamConfig::DEFAULT>(red_arm_param)));
//#line 235 "/opt/ros/jade/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 235 "/opt/ros/jade/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(RedArmParamConfig::AbstractGroupDescriptionConstPtr(new RedArmParamConfig::GroupDescription<RedArmParamConfig::DEFAULT, RedArmParamConfig>(Default)));
//#line 353 "/opt/ros/jade/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<RedArmParamConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<RedArmParamConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<RedArmParamConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    RedArmParamConfig __max__;
    RedArmParamConfig __min__;
    RedArmParamConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const RedArmParamConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static RedArmParamConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &RedArmParamConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const RedArmParamConfig &RedArmParamConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const RedArmParamConfig &RedArmParamConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const RedArmParamConfig &RedArmParamConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<RedArmParamConfig::AbstractParamDescriptionConstPtr> &RedArmParamConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<RedArmParamConfig::AbstractGroupDescriptionConstPtr> &RedArmParamConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const RedArmParamConfigStatics *RedArmParamConfig::__get_statics__()
  {
    const static RedArmParamConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = RedArmParamConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __REDARMPARAMRECONFIGURATOR_H__
