// Generated by gencpp from file gazebo_msgs/AddForceSensor.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_MESSAGE_ADDFORCESENSOR_H
#define GAZEBO_MSGS_MESSAGE_ADDFORCESENSOR_H

#include <ros/service_traits.h>


#include <gazebo_msgs/AddForceSensorRequest.h>
#include <gazebo_msgs/AddForceSensorResponse.h>


namespace gazebo_msgs
{

struct AddForceSensor
{

typedef AddForceSensorRequest Request;
typedef AddForceSensorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddForceSensor
} // namespace gazebo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs::AddForceSensor > {
  static const char* value()
  {
    return "925708c6a561d87c6886f8b30afab5d6";
  }

  static const char* value(const ::gazebo_msgs::AddForceSensor&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs::AddForceSensor > {
  static const char* value()
  {
    return "gazebo_msgs/AddForceSensor";
  }

  static const char* value(const ::gazebo_msgs::AddForceSensor&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs::AddForceSensorRequest> should match 
// service_traits::MD5Sum< ::gazebo_msgs::AddForceSensor > 
template<>
struct MD5Sum< ::gazebo_msgs::AddForceSensorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::AddForceSensor >::value();
  }
  static const char* value(const ::gazebo_msgs::AddForceSensorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::AddForceSensorRequest> should match 
// service_traits::DataType< ::gazebo_msgs::AddForceSensor > 
template<>
struct DataType< ::gazebo_msgs::AddForceSensorRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::AddForceSensor >::value();
  }
  static const char* value(const ::gazebo_msgs::AddForceSensorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs::AddForceSensorResponse> should match 
// service_traits::MD5Sum< ::gazebo_msgs::AddForceSensor > 
template<>
struct MD5Sum< ::gazebo_msgs::AddForceSensorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::AddForceSensor >::value();
  }
  static const char* value(const ::gazebo_msgs::AddForceSensorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::AddForceSensorResponse> should match 
// service_traits::DataType< ::gazebo_msgs::AddForceSensor > 
template<>
struct DataType< ::gazebo_msgs::AddForceSensorResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::AddForceSensor >::value();
  }
  static const char* value(const ::gazebo_msgs::AddForceSensorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_MESSAGE_ADDFORCESENSOR_H
