// Generated by gencpp from file gazebo_msgs/AddJointRequest.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_MESSAGE_ADDJOINTREQUEST_H
#define GAZEBO_MSGS_MESSAGE_ADDJOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_msgs
{
template <class ContainerAllocator>
struct AddJointRequest_
{
  typedef AddJointRequest_<ContainerAllocator> Type;

  AddJointRequest_()
    : name()
    , effort_time(0.0)  {
    }
  AddJointRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , effort_time(0.0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef double _effort_time_type;
  _effort_time_type effort_time;




  typedef boost::shared_ptr< ::gazebo_msgs::AddJointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_msgs::AddJointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddJointRequest_

typedef ::gazebo_msgs::AddJointRequest_<std::allocator<void> > AddJointRequest;

typedef boost::shared_ptr< ::gazebo_msgs::AddJointRequest > AddJointRequestPtr;
typedef boost::shared_ptr< ::gazebo_msgs::AddJointRequest const> AddJointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_msgs::AddJointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_msgs::AddJointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gazebo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/jade/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/jade/share/trajectory_msgs/cmake/../msg'], 'gazebo_msgs': ['/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/existing_packages/gazebo_ros_pkgs/gazebo_msgs/msg'], 'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_msgs::AddJointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_msgs::AddJointRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_msgs::AddJointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_msgs::AddJointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_msgs::AddJointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_msgs::AddJointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_msgs::AddJointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "368cf94519744310de8602f5f382c43f";
  }

  static const char* value(const ::gazebo_msgs::AddJointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x368cf94519744310ULL;
  static const uint64_t static_value2 = 0xde8602f5f382c43fULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_msgs::AddJointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_msgs/AddJointRequest";
  }

  static const char* value(const ::gazebo_msgs::AddJointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_msgs::AddJointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
float64 effort_time\n\
";
  }

  static const char* value(const ::gazebo_msgs::AddJointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_msgs::AddJointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.effort_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AddJointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_msgs::AddJointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_msgs::AddJointRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "effort_time: ";
    Printer<double>::stream(s, indent + "  ", v.effort_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_MSGS_MESSAGE_ADDJOINTREQUEST_H
