// Generated by gencpp from file gazebo_msgs/AddJoint.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_MESSAGE_ADDJOINT_H
#define GAZEBO_MSGS_MESSAGE_ADDJOINT_H

#include <ros/service_traits.h>


#include <gazebo_msgs/AddJointRequest.h>
#include <gazebo_msgs/AddJointResponse.h>


namespace gazebo_msgs
{

struct AddJoint
{

typedef AddJointRequest Request;
typedef AddJointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddJoint
} // namespace gazebo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs::AddJoint > {
  static const char* value()
  {
    return "368cf94519744310de8602f5f382c43f";
  }

  static const char* value(const ::gazebo_msgs::AddJoint&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs::AddJoint > {
  static const char* value()
  {
    return "gazebo_msgs/AddJoint";
  }

  static const char* value(const ::gazebo_msgs::AddJoint&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs::AddJointRequest> should match 
// service_traits::MD5Sum< ::gazebo_msgs::AddJoint > 
template<>
struct MD5Sum< ::gazebo_msgs::AddJointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::AddJoint >::value();
  }
  static const char* value(const ::gazebo_msgs::AddJointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::AddJointRequest> should match 
// service_traits::DataType< ::gazebo_msgs::AddJoint > 
template<>
struct DataType< ::gazebo_msgs::AddJointRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::AddJoint >::value();
  }
  static const char* value(const ::gazebo_msgs::AddJointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs::AddJointResponse> should match 
// service_traits::MD5Sum< ::gazebo_msgs::AddJoint > 
template<>
struct MD5Sum< ::gazebo_msgs::AddJointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::AddJoint >::value();
  }
  static const char* value(const ::gazebo_msgs::AddJointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::AddJointResponse> should match 
// service_traits::DataType< ::gazebo_msgs::AddJoint > 
template<>
struct DataType< ::gazebo_msgs::AddJointResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::AddJoint >::value();
  }
  static const char* value(const ::gazebo_msgs::AddJointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_MESSAGE_ADDJOINT_H
