// Generated by gencpp from file gazebo_msgs/AddLink.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_MESSAGE_ADDLINK_H
#define GAZEBO_MSGS_MESSAGE_ADDLINK_H

#include <ros/service_traits.h>


#include <gazebo_msgs/AddLinkRequest.h>
#include <gazebo_msgs/AddLinkResponse.h>


namespace gazebo_msgs
{

struct AddLink
{

typedef AddLinkRequest Request;
typedef AddLinkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddLink
} // namespace gazebo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs::AddLink > {
  static const char* value()
  {
    return "ec8df5ac806767963e931886ff3d220b";
  }

  static const char* value(const ::gazebo_msgs::AddLink&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs::AddLink > {
  static const char* value()
  {
    return "gazebo_msgs/AddLink";
  }

  static const char* value(const ::gazebo_msgs::AddLink&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs::AddLinkRequest> should match 
// service_traits::MD5Sum< ::gazebo_msgs::AddLink > 
template<>
struct MD5Sum< ::gazebo_msgs::AddLinkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::AddLink >::value();
  }
  static const char* value(const ::gazebo_msgs::AddLinkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::AddLinkRequest> should match 
// service_traits::DataType< ::gazebo_msgs::AddLink > 
template<>
struct DataType< ::gazebo_msgs::AddLinkRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::AddLink >::value();
  }
  static const char* value(const ::gazebo_msgs::AddLinkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs::AddLinkResponse> should match 
// service_traits::MD5Sum< ::gazebo_msgs::AddLink > 
template<>
struct MD5Sum< ::gazebo_msgs::AddLinkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::AddLink >::value();
  }
  static const char* value(const ::gazebo_msgs::AddLinkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::AddLinkResponse> should match 
// service_traits::DataType< ::gazebo_msgs::AddLink > 
template<>
struct DataType< ::gazebo_msgs::AddLinkResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::AddLink >::value();
  }
  static const char* value(const ::gazebo_msgs::AddLinkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_MESSAGE_ADDLINK_H
