// Generated by gencpp from file gazebo_msgs/StartTimer.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_MESSAGE_STARTTIMER_H
#define GAZEBO_MSGS_MESSAGE_STARTTIMER_H

#include <ros/service_traits.h>


#include <gazebo_msgs/StartTimerRequest.h>
#include <gazebo_msgs/StartTimerResponse.h>


namespace gazebo_msgs
{

struct StartTimer
{

typedef StartTimerRequest Request;
typedef StartTimerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartTimer
} // namespace gazebo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs::StartTimer > {
  static const char* value()
  {
    return "8ff7d44c34992c271801e5f640dcfa8d";
  }

  static const char* value(const ::gazebo_msgs::StartTimer&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs::StartTimer > {
  static const char* value()
  {
    return "gazebo_msgs/StartTimer";
  }

  static const char* value(const ::gazebo_msgs::StartTimer&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs::StartTimerRequest> should match 
// service_traits::MD5Sum< ::gazebo_msgs::StartTimer > 
template<>
struct MD5Sum< ::gazebo_msgs::StartTimerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::StartTimer >::value();
  }
  static const char* value(const ::gazebo_msgs::StartTimerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::StartTimerRequest> should match 
// service_traits::DataType< ::gazebo_msgs::StartTimer > 
template<>
struct DataType< ::gazebo_msgs::StartTimerRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::StartTimer >::value();
  }
  static const char* value(const ::gazebo_msgs::StartTimerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs::StartTimerResponse> should match 
// service_traits::MD5Sum< ::gazebo_msgs::StartTimer > 
template<>
struct MD5Sum< ::gazebo_msgs::StartTimerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::StartTimer >::value();
  }
  static const char* value(const ::gazebo_msgs::StartTimerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::StartTimerResponse> should match 
// service_traits::DataType< ::gazebo_msgs::StartTimer > 
template<>
struct DataType< ::gazebo_msgs::StartTimerResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::StartTimer >::value();
  }
  static const char* value(const ::gazebo_msgs::StartTimerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_MESSAGE_STARTTIMER_H
