// Generated by gencpp from file gazebo_msgs/StartTimerRequest.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_MESSAGE_STARTTIMERREQUEST_H
#define GAZEBO_MSGS_MESSAGE_STARTTIMERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_msgs
{
template <class ContainerAllocator>
struct StartTimerRequest_
{
  typedef StartTimerRequest_<ContainerAllocator> Type;

  StartTimerRequest_()
    : duration_write_joint_states(0.0)
    , duration_update_link_states(0.0)
    , duration_read_joint_efforts(0.0)
    , duration_write_forces(0.0)  {
    }
  StartTimerRequest_(const ContainerAllocator& _alloc)
    : duration_write_joint_states(0.0)
    , duration_update_link_states(0.0)
    , duration_read_joint_efforts(0.0)
    , duration_write_forces(0.0)  {
    }



   typedef double _duration_write_joint_states_type;
  _duration_write_joint_states_type duration_write_joint_states;

   typedef double _duration_update_link_states_type;
  _duration_update_link_states_type duration_update_link_states;

   typedef double _duration_read_joint_efforts_type;
  _duration_read_joint_efforts_type duration_read_joint_efforts;

   typedef double _duration_write_forces_type;
  _duration_write_forces_type duration_write_forces;




  typedef boost::shared_ptr< ::gazebo_msgs::StartTimerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_msgs::StartTimerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartTimerRequest_

typedef ::gazebo_msgs::StartTimerRequest_<std::allocator<void> > StartTimerRequest;

typedef boost::shared_ptr< ::gazebo_msgs::StartTimerRequest > StartTimerRequestPtr;
typedef boost::shared_ptr< ::gazebo_msgs::StartTimerRequest const> StartTimerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_msgs::StartTimerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_msgs::StartTimerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gazebo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/jade/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/jade/share/trajectory_msgs/cmake/../msg'], 'gazebo_msgs': ['/home/bilynbk/catkin_ws_ahl/src/ahl_ros_packages/existing_packages/gazebo_ros_pkgs/gazebo_msgs/msg'], 'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_msgs::StartTimerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_msgs::StartTimerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_msgs::StartTimerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_msgs::StartTimerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_msgs::StartTimerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_msgs::StartTimerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_msgs::StartTimerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ff7d44c34992c271801e5f640dcfa8d";
  }

  static const char* value(const ::gazebo_msgs::StartTimerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ff7d44c34992c27ULL;
  static const uint64_t static_value2 = 0x1801e5f640dcfa8dULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_msgs::StartTimerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_msgs/StartTimerRequest";
  }

  static const char* value(const ::gazebo_msgs::StartTimerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_msgs::StartTimerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 duration_write_joint_states\n\
float64 duration_update_link_states\n\
float64 duration_read_joint_efforts\n\
float64 duration_write_forces\n\
";
  }

  static const char* value(const ::gazebo_msgs::StartTimerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_msgs::StartTimerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.duration_write_joint_states);
      stream.next(m.duration_update_link_states);
      stream.next(m.duration_read_joint_efforts);
      stream.next(m.duration_write_forces);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct StartTimerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_msgs::StartTimerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_msgs::StartTimerRequest_<ContainerAllocator>& v)
  {
    s << indent << "duration_write_joint_states: ";
    Printer<double>::stream(s, indent + "  ", v.duration_write_joint_states);
    s << indent << "duration_update_link_states: ";
    Printer<double>::stream(s, indent + "  ", v.duration_update_link_states);
    s << indent << "duration_read_joint_efforts: ";
    Printer<double>::stream(s, indent + "  ", v.duration_read_joint_efforts);
    s << indent << "duration_write_forces: ";
    Printer<double>::stream(s, indent + "  ", v.duration_write_forces);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_MSGS_MESSAGE_STARTTIMERREQUEST_H
