(cl:in-package gazebo_msgs-srv)
(cl:export '(DURATION_WRITE_JOINT_STATES-VAL
          DURATION_WRITE_JOINT_STATES
          DURATION_UPDATE_LINK_STATES-VAL
          DURATION_UPDATE_LINK_STATES
          DURATION_READ_JOINT_EFFORTS-VAL
          DURATION_READ_JOINT_EFFORTS
          DURATION_WRITE_FORCES-VAL
          DURATION_WRITE_FORCES
))